on:
    push:
        branches:
            - main
    pull_request:
jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'

            - name: Build
              run: |
                  npm i
                  npm run build
                  npx build-storybook -o ./docs/components/storybook

            - name: Deploy docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: test-gh-pages-branch
                  publish_dir: ./docs
